# Generated by Django 4.2.1 on 2023-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('measurements', models.CharField(max_length=100)),
                ('fabricType', models.CharField(max_length=100)),
                ('deliveryOption', models.CharField(max_length=100)),
            ],
        ),
    ]
